### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by iwantmods82** [HolyHades/VanillaEnhanced#7]
maybe try adding a new turret designed for crowd control? i dont know what it should require or fire, but here is something for it
i had some ideas for it's code, and here they are:
{
    Type:turret
    Name:blast
    Description:an makeshift multi shot cannon. idea by user 'me'
    Research:scatter
    Spread:8.5
    Shots:12 
                            }
feel free to add whatever code you want after these recommendations :)

**Comment by scuba323** [comment]
@iwantmods82 why not just do a pull request, or fork and manage your own. Not sure what this is going to accomplish ☺️

**Comment by HolyHades** [comment]
fully agree with scuba323, i'm gonna close this.
